// UI text for the session view, in the language the lesson is being taught
// in. Scope is deliberate: the screen where a German conversation is
// happening should not be captioned in English. The recap's own content
// already comes back translated from the grader.
//
// Placeholders are {name}, {them}, {topic} — filled by t().

const STRINGS = {
  en: {
    ready: "{name} is ready. Press the microphone and start teaching {them} about {topic}.",
    pressMic: "Press the microphone and start explaining.",
    connecting: "Connecting to {name}...",
    speaking: "🔊 {name} is speaking...",
    listening: "🎙️ {name} is listening...",
    thinking: "💭 {name} is thinking...",
    startTeaching: "🎙️ Start teaching {name}...",
    muted: "🔇 Microphone muted — {name} can't hear you.",
    restingHint: "🤔 Take your time — {name} is waiting quietly.",
    isSpeaking: "{name} is speaking",
    isListening: "{name} is listening",
    isThinking: "{name} is thinking",
    waiting: "waiting for you",
    yourLesson: "YOUR LESSON",
    pointsMentioned: "POINTS MENTIONED",
    challenge: "CHALLENGE {them}",
    commonWrong: "WHAT BEGINNERS USUALLY GET WRONG",
    dontSay: "DON'T SAY",
    micUnmute: "Unmute your microphone",
    micMute: "Mute your microphone",
    pauseHint: "Take a moment. {name} waits, and won't ask if you're still there",
    resumeHint: "Carry on — {name} starts listening again",
    endCallHint: "End the conversation",
    bannedSlipped: "{count} slipped through — that's fine, keep going.",
    taughtBy: "taught by",
    voiceOnly: "🎙️ Voice only",
    showPanels: "🗒️ Show the panels",
    letMeThink: "🤔 Let me think",
    imReady: "▶︎ I'm ready",
    endCall: "⏹️ End conversation",
    askUnderstood: "{glyph} Ask {name} what {they} understood",
    asked: "{glyph} Asked — listen to what {they} got",
    recallHint: "{name} will say back what {they} thinks {they} understood",
    finish: "Finish lesson →",
    seeNotes: "See {name}'s Notes →",
    teachSomethingElse: "← Teach something else",
    justTalk: "Just talk. {name} will tell you what {they} understood at the end.",
    coveredAll: "You covered all four points.",
    confidenceQ: "Before you start — how well do you think you know {topic}?",
    confShaky: "Shaky",
    confOk: "Pretty well",
    confStrong: "I could teach it",
    conceptDensity: "Concept density",
    prerequisites: "Prerequisites",
    Beginner: "Beginner",
    Intermediate: "Intermediate",
    Advanced: "Advanced",
    butDid: "But did {name} actually follow it? Finish the lesson and {they}'ll tell you.",

    // Landing page. The product name itself stays English — it is the
    // brand, not a sentence.
    heroLine1: "If you can't explain it",
    heroLine2: "to {name},",
    heroLine3: "do you really understand it?",
    heroSub: "Name anything you know. Then try to teach it to someone who knows absolutely nothing about it.",
    createCharacter: "Create your character",
    editCharacter: "Edit your character",
    whoTeaching: "Who are you teaching?",
    whatTeach: "What do you want to teach?",
    teachIn: "Teach in",
    topicPlaceholder: "Backpropagation, embeddings, why transformers replaced RNNs…",
    teachIt: "Teach it →",
    preparing: "Preparing…",
    workingOut: "Working out what {name} would need to hear…",
    gotCode: "Got a Teach-Off code?",
    yourName: "Your name",
    join: "Join →",
    orTry: "Or try",
    clearLesson: "Clear saved lesson",
    resetAll: "Reset everything",
    presetHint: "Start from this one, then tweak",
    clearLessonHint: "Clears any half-finished lesson still saved in this tab. Keeps your name, XP and badges.",
    resetAllHint: "Deletes your name, face, XP and badges as well",
    resetAllConfirm: "Clear everything?\n\nYour name, face, XP and badges will be deleted. This can't be undone.",
    dropped: "{name} hung up. Press the microphone to carry on — nothing you said is lost.",
    you: "YOU",
    // Recap
    // The caller passes an already-uppercased name; uppercasing the
    // template here instead would break the {name} placeholder itself.
    notesOf: "{name}'S NOTES",
    recapSub: "Here's what {name} understood from your lesson on",
    feynmanScore: "FEYNMAN SCORE",
    says: "{name} SAYS",
    marking: "{name} is marking your lesson…",
    reallyUnderstand: "Did {name} really understand?",
    predictTitle: "What it expected you to struggle with",
    predictIntro: "Predicted before you said a word, from the topic alone.",
    asPredicted: "as predicted",
    caughtYouOut: "caught you out",
    youBeatIt: "you beat it",
    expectedYouGot: "expected {level} · you got it across",
    expectedYouDidnt: "expected {level} · you did not",
    depthTitle: "How deep you went",
    youGotHere: "you got here",
    nextRung: "Next rung:",
    blindTitle: "What you never went near",
    blindIntro: "Not explained badly — never mentioned at all.",
    juryTitle: "The jury",
    juryIntro: "Four listeners, four standards. The same explanation can land for one and fail for another.",
    convene: "Convene the jury →",
    explainBackTitle: "Let me see if I understood you",
    recallAsk:
      "{name}, before I go — can you tell me back what you understood, in your own words?",
    youCovered: "You covered",
    theyFollowed: "{name} followed",
    couldRepeat: "{they} could repeat back",
    gapLadder:
      "Each step is a harder test than the one before it. Repeating your words back is not the same as following them.",
    tookAway: "What {name} took away",
    saidOutLoud: "What {name} said out loud",
    undefinedWords: "Words you used but never explained",
    fromYourOwn: "Every word above came from your own explanation.",
    strongest: "Your strongest moment",
    theyFollowedTitle: "What {name} followed",
    toImprove: "What to improve",
    neededHelp: "Where {name} needed help",
    yourExplanation: "Your explanation",
    turnedTitle: "Where it turned",
    turnedIntro: "The moments that decided this lesson, in the order they happened.",
    deliveryTitle: "How you said it",
    mirrorTitle: "Now check {theirs} work",
    mirrorIntro: "{name} retells your lesson — with a couple of things deliberately wrong. Catch them.",
    mirrorStart: "🪞 Let's hear it →",
    teachoffTitle: "Think someone can beat that?",
    teachoffIntro: "They teach the exact same lesson, {name} grades them the same way, one board settles it.",
    startTeachoff: "⚔️ Start a Teach-Off",
    runTitle: "The run",
    taughtTo: "taught to {name}",
    scoreLabel: "Feynman score",
    pointsFollowed: "points followed",
    onTheMic: "on the mic",
    xpEarned: "XP earned",
    copySummary: "Copy summary",
    takeChallenge: "🎯 Take the challenge →",
    predictedLabel: "You predicted",
    measuredLabel: "Measured",
    trapTitle: "The trap {name} set",
    thisTeachoff: "This Teach-Off",


    // Character builder
    yourCharacter: "Your character",
    hair: "Hair",
    facialHair: "Facial hair",
    glasses: "Glasses",
    expression: "Expression",
    skin: "Skin",
    backdrop: "Backdrop",
    thatsMe: "That's me →",
    saving: "Saving…",
  },

  de: {
    ready: "{name} ist bereit. Drücke das Mikrofon und erkläre {them} {topic}.",
    pressMic: "Drücke das Mikrofon und fang an zu erklären.",
    connecting: "Verbinde mit {name}...",
    speaking: "🔊 {name} spricht...",
    listening: "🎙️ {name} hört zu...",
    thinking: "💭 {name} denkt nach...",
    startTeaching: "🎙️ Fang an, {name} zu unterrichten...",
    muted: "🔇 Mikrofon stumm — {name} kann dich nicht hören.",
    restingHint: "🤔 Lass dir Zeit — {name} wartet ruhig.",
    isSpeaking: "{name} spricht",
    isListening: "{name} hört zu",
    isThinking: "{name} denkt nach",
    waiting: "wartet auf dich",
    yourLesson: "DEINE LEKTION",
    pointsMentioned: "GENANNTE PUNKTE",
    challenge: "FORDERE {themAcc} HERAUS",
    commonWrong: "WAS ANFÄNGER MEIST FALSCH VERSTEHEN",
    dontSay: "NICHT SAGEN",
    micUnmute: "Mikrofon wieder anschalten",
    micMute: "Mikrofon stummschalten",
    pauseHint: "Lass dir Zeit. {name} wartet und fragt nicht nach, ob du noch da bist",
    resumeHint: "Weiter — {name} hört wieder zu",
    endCallHint: "Das Gespräch beenden",
    bannedSlipped: "{count} durchgerutscht — kein Problem, mach weiter.",
    taughtBy: "unterrichtet von",
    voiceOnly: "🎙️ Nur Stimme",
    showPanels: "🗒️ Panels zeigen",
    letMeThink: "🤔 Lass mich überlegen",
    imReady: "▶︎ Ich bin bereit",
    endCall: "⏹️ Gespräch beenden",
    askUnderstood: "{glyph} Frag {name}, was {they} verstanden hat",
    asked: "{glyph} Gefragt — hör zu, was {they} verstanden hat",
    recallHint: "{name} sagt dir, was {they} verstanden zu haben glaubt",
    finish: "Lektion beenden →",
    seeNotes: "Notizen von {name} ansehen →",
    teachSomethingElse: "← Etwas anderes erklären",
    justTalk: "Sprich einfach. {name} sagt dir am Ende, was {they} verstanden hat.",
    coveredAll: "Du hast alle vier Punkte angesprochen.",
    confidenceQ: "Bevor du anfängst — wie gut kennst du {topic} deiner Meinung nach?",
    confShaky: "Wackelig",
    confOk: "Ganz gut",
    confStrong: "Ich könnte es unterrichten",
    conceptDensity: "Konzeptdichte",
    prerequisites: "Vorkenntnisse",
    Beginner: "Anfänger",
    Intermediate: "Mittel",
    Advanced: "Fortgeschritten",
    butDid: "Aber hat {name} es wirklich verstanden? Beende die Lektion und du erfährst es.",

    heroLine1: "Wenn du es",
    heroLine2: "{name} nicht erklären kannst,",
    heroLine3: "verstehst du es dann wirklich?",
    heroSub: "Nenne etwas, das du kennst. Dann erkläre es jemandem, der absolut nichts darüber weiß.",
    createCharacter: "Erstelle deinen Charakter",
    editCharacter: "Charakter bearbeiten",
    whoTeaching: "Wem erklärst du es?",
    whatTeach: "Was möchtest du erklären?",
    teachIn: "Sprache",
    topicPlaceholder: "Backpropagation, Embeddings, warum Transformer RNNs abgelöst haben…",
    teachIt: "Los geht's →",
    preparing: "Wird vorbereitet…",
    workingOut: "Überlege, was {name} hören müsste…",
    gotCode: "Hast du einen Teach-Off-Code?",
    yourName: "Dein Name",
    join: "Beitreten →",
    orTry: "Oder probiere",
    clearLesson: "Gespeicherte Lektion löschen",
    resetAll: "Alles zurücksetzen",
    presetHint: "Hiermit anfangen und dann anpassen",
    clearLessonHint: "Löscht eine angefangene Lektion in diesem Tab. Name, XP und Abzeichen bleiben.",
    resetAllHint: "Löscht auch deinen Namen, dein Gesicht, XP und Abzeichen",
    resetAllConfirm: "Alles löschen?\n\nName, Gesicht, XP und Abzeichen werden gelöscht. Das lässt sich nicht rückgängig machen.",
    dropped: "{name} hat aufgelegt. Drücke das Mikrofon, um weiterzumachen — nichts geht verloren.",
    you: "DU",
    notesOf: "NOTIZEN VON {name}",
    recapSub: "Das hat {name} aus deiner Lektion mitgenommen:",
    feynmanScore: "FEYNMAN-SCORE",
    says: "{name} SAGT",
    marking: "{name} bewertet deine Lektion…",
    reallyUnderstand: "Hat {name} es wirklich verstanden?",
    predictTitle: "Womit du laut Vorhersage Mühe haben würdest",
    predictIntro: "Vorhergesagt, bevor du ein Wort gesagt hast — allein aus dem Thema.",
    asPredicted: "wie vorhergesagt",
    caughtYouOut: "hat dich erwischt",
    youBeatIt: "du warst besser",
    expectedYouGot: "erwartet: {level} · du hast es rübergebracht",
    expectedYouDidnt: "erwartet: {level} · du nicht",
    depthTitle: "Wie tief du gegangen bist",
    youGotHere: "bis hierher",
    nextRung: "Nächste Stufe:",
    blindTitle: "Was du gar nicht angesprochen hast",
    blindIntro: "Nicht schlecht erklärt — überhaupt nicht erwähnt.",
    juryTitle: "Die Jury",
    juryIntro: "Vier Zuhörer, vier Maßstäbe. Dieselbe Erklärung kann bei einem ankommen und beim anderen scheitern.",
    convene: "Jury einberufen →",
    explainBackTitle: "Mal sehen, ob ich dich verstanden habe",
    recallAsk:
      "{name}, bevor ich gehe — kannst du mir in deinen eigenen Worten sagen, was du verstanden hast?",
    youCovered: "Du hast angesprochen",
    theyFollowed: "{name} ist gefolgt",
    couldRepeat: "{they} konnte wiedergeben",
    gapLadder:
      "Jede Stufe ist eine härtere Prüfung als die vorige. Deine Worte wiederzugeben heißt nicht, sie verstanden zu haben.",
    tookAway: "Was {name} mitgenommen hat",
    saidOutLoud: "Was {name} laut gesagt hat",
    undefinedWords: "Wörter, die du benutzt, aber nie erklärt hast",
    fromYourOwn: "Jedes Wort oben stammt aus deiner eigenen Erklärung.",
    strongest: "Dein stärkster Moment",
    theyFollowedTitle: "Was {name} verstanden hat",
    toImprove: "Was besser werden kann",
    neededHelp: "Wo {name} Hilfe brauchte",
    yourExplanation: "Deine Erklärung",
    turnedTitle: "Wo es sich entschieden hat",
    turnedIntro: "Die Momente, die diese Lektion entschieden haben, in ihrer Reihenfolge.",
    deliveryTitle: "Wie du es gesagt hast",
    mirrorTitle: "Jetzt prüfe die Version von {name}",
    mirrorIntro: "{name} erzählt deine Lektion nach — mit ein paar absichtlichen Fehlern. Finde sie.",
    mirrorStart: "🪞 Auf geht's →",
    teachoffTitle: "Glaubst du, jemand macht es besser?",
    teachoffIntro: "Dieselbe Lektion, dieselbe Bewertung durch {name}, eine Rangliste entscheidet.",
    startTeachoff: "⚔️ Teach-Off starten",
    runTitle: "Der Durchgang",
    taughtTo: "erklärt an {name}",
    scoreLabel: "Feynman-Score",
    pointsFollowed: "Punkte verstanden",
    onTheMic: "am Mikrofon",
    xpEarned: "XP verdient",
    copySummary: "Zusammenfassung kopieren",
    takeChallenge: "🎯 Herausforderung annehmen →",
    predictedLabel: "Deine Einschätzung",
    measuredLabel: "Gemessen",
    trapTitle: "Die Falle von {name}",
    thisTeachoff: "Dieser Teach-Off",


    yourCharacter: "Dein Charakter",
    hair: "Haare",
    facialHair: "Bart",
    glasses: "Brille",
    expression: "Gesichtsausdruck",
    skin: "Hautton",
    backdrop: "Hintergrund",
    thatsMe: "Das bin ich →",
    saving: "Wird gespeichert…",
  },
};

// German needs the right pronoun case, and it differs from English: the
// object form after "erkläre" is dative, and subject pronouns differ by
// gender. Kept beside the strings so a new character can't forget them.
const PRONOUNS = {
  en: {
    she: { they: "she", them: "her", themAcc: "her" },
    he: { they: "he", them: "him", themAcc: "him" },
  },
  de: {
    // them = dative (erkläre IHR), themAcc = accusative (fordere SIE heraus)
    she: { they: "sie", them: "ihr", themAcc: "sie" },
    he: { they: "er", them: "ihm", themAcc: "ihn" },
  },
};

export function t(language, key, vars = {}) {
  const table = STRINGS[language] ?? STRINGS.en;
  const template = table[key] ?? STRINGS.en[key] ?? key;

  return template.replace(/\{(\w+)\}/g, (whole, name) =>
    name in vars ? String(vars[name]) : whole
  );
}

// The vars every session string needs, derived from the active character.
export function speakerVars(language, character) {
  const set =
    PRONOUNS[language]?.[character.subj] ?? PRONOUNS.en[character.subj];

  return {
    name: character.shortName,
    glyph: character.glyph,
    they: set.they,
    them: set.them,
    themAcc: set.themAcc,
  };
}
